swagger: "2.0"
info:
  title: "API Server"
  description: "API documentation for User management and health check"
  version: "1.0.0"
paths:
  /health:
    get:
      summary: "Health Check"
      responses:
        200:
          description: "API is running"
  /users/add:
    post:
      summary: "Add a user"
      parameters:
        - in: body
          name: user
          description: "User object to add"
          schema:
            $ref: "#/definitions/User"
      responses:
        201:
          description: "User added successfully"
  /users/{id}:
    get:
      summary: "Get user by ID"
      parameters:
        - in: path
          name: id
          type: integer
          required: true
          description: "User ID"
      responses:
        200:
          description: "User found"
        404:
          description: "User not found"
definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
      email:
        type: "string"
