services:
  selenium-hub:
    image: selenium/hub:4.35.0
    platform: linux/amd64
    container_name: selenium-hub
    ports:
      - "4442-4444:4442-4444"
    networks:
      - app-net

  chrome:
    image: selenium/node-chrome:4.35.0
    platform: linux/amd64
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - app-net

  firefox:
    image: selenium/node-firefox:4.35.0
    platform: linux/amd64
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - app-net

  edge:
    image: selenium/node-edge:4.35.0
    platform: linux/amd64
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - app-net

volumes:
  postgres_data:

networks:
  app-net:
    external:
      name: java-selenium-cucumber-react_app-net