services:
  postgres:
    image: postgres:latest
    container_name: test-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: automation_engine_cucumber_react
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
