services:
  # Selenium Grid Hub
  selenium-hub:
    image: selenium/hub:4.21.0
    platform: linux/amd64
    container_name: selenium-hub
    ports:
      - "4442-4444:4442-4444"
    environment:
      - SE_SESSION_REQUEST_TIMEOUT=300
      - SE_SESSION_RETRY_INTERVAL=15
      - SE_HEALTHCHECK_INTERVAL=30
      - SE_ENABLE_TRACING=false
      - SE_LOG_LEVEL=INFO
    volumes:
      - /dev/shm:/dev/shm
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - selenium-net
    restart: unless-stopped

  # Chrome Node
  chrome-node:
    image: selenium/node-chrome:4.21.0
    platform: linux/amd64
    container_name: selenium-node-chrome
    shm_size: 2gb
    depends_on:
      selenium-hub:
        condition: service_healthy
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_INSTANCES=2
      - SE_NODE_MAX_SESSIONS=2
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_LOG_LEVEL=INFO
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - selenium-net
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 512m

  # Firefox Node
  firefox-node:
    image: selenium/node-firefox:4.21.0
    platform: linux/amd64
    container_name: selenium-node-firefox
    shm_size: 2gb
    depends_on:
      selenium-hub:
        condition: service_healthy
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_INSTANCES=2
      - SE_NODE_MAX_SESSIONS=2
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_LOG_LEVEL=INFO
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - selenium-net
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 512m

  # Edge Node
  edge-node:
    image: selenium/node-edge:4.21.0
    platform: linux/amd64
    container_name: selenium-node-edge
    shm_size: 2gb
    depends_on:
      selenium-hub:
        condition: service_healthy
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_INSTANCES=2
      - SE_NODE_MAX_SESSIONS=2
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_LOG_LEVEL=INFO
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - selenium-net
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 512m

networks:
  selenium-net:
    external: true
    name: selenium_selenium-net