package com.framework.apiserver.service;

import com.framework.apiserver.config.KafkaProperties;
import com.framework.apiserver.dto.*;
import com.framework.apiserver.service.impl.TestExecutionServiceImpl;
import com.framework.apiserver.service.impl.TestRerunServiceImpl;
import com.framework.apiserver.utilities.AsyncJobManager;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.stereotype.Service;

/**
 * Orchestrator service that decides whether to use Kafka or Thread-based execution
 * based on configuration and availability
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class ExecutionOrchestratorService {

    private final KafkaProperties kafkaProperties;
    private final KafkaProducer kafkaProducerService;
    private final TestExecutionServiceImpl testExecutionService;
    private final TestRerunServiceImpl testRerunService;
    private final AsyncJobManager asyncJobManager;
    private final BrowserContextManager browserContextManager;

    /**
     * Execute tests using the best available method (Kafka or Threads)
     */
    public String executeTestsAsync(String tag, String createdBy) {
        String jobId = asyncJobManager.createJobWithTracking(null, tag, createdBy);

        if (shouldUseKafka()) {
            return executeTestsViaKafka(jobId, tag, createdBy);
        } else {
            log.info("Using thread-based execution as fallback for jobId: {}", jobId);
            return executeTestsViaThread(jobId, tag, createdBy);
        }
    }

    /**
     * Execute test rerun using the best available method
     */
    public String executeRerunAsync(String originalRunId, String createdBy, boolean failedOnly) {
        String jobId = asyncJobManager.createJobWithTracking(originalRunId, "Rerun", createdBy);

        if (shouldUseKafka()) {
            return executeRerunViaKafka(jobId, originalRunId, createdBy, failedOnly);
        } else {
            log.info("Using thread-based execution as fallback for rerun jobId: {}", jobId);
            return executeRerunViaThread(jobId, originalRunId, createdBy, failedOnly);
        }
    }

    /**
     * Execute tests via Kafka
     */
    private String executeTestsViaKafka(String jobId, String tag, String createdBy) {
        try {
            TestExecutionRequest request = new TestExecutionRequest(
                    jobId,
                    null, // runId will be generated by consumer
                    tag,
                    createdBy,
                    browserContextManager.getBrowserType()
            );

            kafkaProducerService.sendTestExecutionRequest(request)
                    .whenComplete((result, ex) -> {
                        if (ex != null) {
                            log.error("Failed to send test execution request to Kafka, falling back to threads", ex);
                            executeTestsViaThread(jobId, tag, createdBy);
                        }
                    });

            log.info("Test execution request sent to Kafka for jobId: {}", jobId);
            return jobId;

        } catch (Exception e) {
            log.error("Failed to send test execution request to Kafka, falling back to threads", e);
            return executeTestsViaThread(jobId, tag, createdBy);
        }
    }

    /**
     * Execute rerun via Kafka
     */
    private String executeRerunViaKafka(String jobId, String originalRunId, String createdBy, boolean failedOnly) {
        try {
            TestRerunRequest request = new TestRerunRequest(
                    jobId,
                    null, // runId will be generated by consumer
                    originalRunId,
                    createdBy,
                    failedOnly
            );

            kafkaProducerService.sendTestRerunRequest(request)
                    .whenComplete((result, ex) -> {
                        if (ex != null) {
                            log.error("Failed to send test rerun request to Kafka, falling back to threads", ex);
                            executeRerunViaThread(jobId, originalRunId, createdBy, failedOnly);
                        }
                    });

            log.info("Test rerun request sent to Kafka for jobId: {}, originalRunId: {}, failedOnly: {}",
                    jobId, originalRunId, failedOnly);
            return jobId;

        } catch (Exception e) {
            log.error("Failed to send test rerun request to Kafka, falling back to threads", e);
            return executeRerunViaThread(jobId, originalRunId, createdBy, failedOnly);
        }
    }

    /**
     * Execute tests via thread (fallback method)
     */
    private String executeTestsViaThread(String jobId, String tag, String createdBy) {
        Thread jobThread = new Thread(() -> {
            asyncJobManager.setJobRunning(jobId);
            try {
                TestExecutionResponse response = testExecutionService.runCucumberTests(tag, jobId, true);
                asyncJobManager.completeJob(jobId, response);
            } catch (Exception e) {
                log.error("Thread-based test execution failed for jobId: {}", jobId, e);
                asyncJobManager.failJob(jobId, e.getMessage());
            }
        });

        jobThread.setName("AsyncTest-" + tag + "-" + jobId.substring(0, 8));
        asyncJobManager.registerJobThread(jobId, jobThread);
        jobThread.start();

        log.info("Started thread-based test execution for jobId: {}", jobId);
        return jobId;
    }

    /**
     * Execute rerun via thread (fallback method)
     */
    private String executeRerunViaThread(String jobId, String originalRunId, String createdBy, boolean failedOnly) {
        Thread jobThread = new Thread(() -> {
            asyncJobManager.setJobRunning(jobId);
            try {
                TestExecutionResponse response;
                if (failedOnly) {
                    response = testRerunService.rerunFailed(originalRunId, createdBy);
                } else {
                    response = testRerunService.rerunAll(originalRunId, jobId);
                }
                asyncJobManager.completeJob(jobId, response);
            } catch (Exception e) {
                log.error("Thread-based test rerun failed for jobId: {}", jobId, e);
                asyncJobManager.failJob(jobId, e.getMessage());
            }
        });

        jobThread.setName("AsyncRerun-" + originalRunId + "-" + jobId.substring(0, 8));
        asyncJobManager.registerJobThread(jobId, jobThread);
        jobThread.start();

        log.info("Started thread-based test rerun for jobId: {}, originalRunId: {}", jobId, originalRunId);
        return jobId;
    }

    /**
     * Determine whether to use Kafka or fall back to threads
     */
    private boolean shouldUseKafka() {
        if (!kafkaProperties.isEnabled()) {
            log.debug("Kafka is disabled in configuration");
            return false;
        }

        try {
            // Check if Kafka is available
            boolean kafkaAvailable = kafkaProducerService.isKafkaAvailable();
            if (!kafkaAvailable && kafkaProperties.isFallbackToThreads()) {
                log.warn("Kafka is not available, falling back to threads");
                return false;
            }
            return kafkaAvailable;
        } catch (Exception e) {
            log.warn("Failed to check Kafka availability", e);
            return kafkaProperties.isFallbackToThreads() ? false : true;
        }
    }

    /**
     * Get execution statistics
     */
    public ExecutionStats getExecutionStats() {
        // Implementation to get stats about Kafka vs Thread usage
        return ExecutionStats.builder()
                .kafkaEnabled(kafkaProperties.isEnabled())
                .kafkaAvailable(shouldUseKafka())
                .fallbackEnabled(kafkaProperties.isFallbackToThreads())
                .build();
    }
}