package com.framework.apiserver.dto;

public enum TestRunEventType {
    TEST_EXECUTION_REQUESTED,
    TEST_RERUN_REQUESTED,
    TEST_FAILED_RERUN_REQUESTED,
    TEST_EXECUTION_STARTED,
    TEST_EXECUTION_COMPLETED,
    TEST_EXECUTION_FAILED,
    TEST_EXECUTION_CANCELLED
}
