name: CI - Trigger Automation via API

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  run-automation:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Set up JDK for Spring Boot
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Build Spring Boot backend
      - name: Build Spring Boot
        run: mvn clean install -DskipTests

      # Start Spring Boot backend in background with JWT secret
      - name: Start Spring Boot backend
        run: mvn spring-boot:run &
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      # Wait for backend startup with 120s timeout
      - name: Wait for backend startup
        run: |
          echo "Waiting for backend to start (max 120s)..."
          for i in $(seq 1 120); do
            if curl -s http://localhost:8080/actuator/health | grep '"status":"UP"' > /dev/null; then
              echo "Backend started!"
              exit 0
            fi
            sleep 1
          done
          echo "Backend did not start within 120 seconds."
          exit 1

      # Generate JWT token and trigger /run-tests
      - name: Trigger automation with JWT
        id: run_tests
        run: |
          echo "Generating JWT token..."
          TOKEN=$(curl -s -X POST http://localhost:8080/api/auth/login \
            -H "Content-Type: application/json" \
            -d '{"username":"${{ secrets.TEST_USER }}","password":"${{ secrets.TEST_PASS }}"}' \
            | jq -r '.token')

          echo "Calling /run-tests API with JWT..."
          RESPONSE=$(curl -s -X POST http://localhost:8080/run-tests \
            -H "Authorization: Bearer $TOKEN" \
            -H "Content-Type: application/json" \
          -d '{"tags":"@smoke_api"}')
          
          echo "Response: $RESPONSE"
          RUN_ID=$(echo "$RESPONSE" | jq -r '.runId')
          echo "Run ID is $RUN_ID"
          echo "run_id=$RUN_ID" >> $GITHUB_ENV

      # Pull test report using runId
      - name: Pull test report
        run: |
          echo "Downloading report for run ID: ${{ env.run_id }}"
          curl -o target/cucumber-reports/report-${{ env.run_id }}.json \
            http://localhost:8080/api/reports/${{ env.run_id }}/download

      # Archive test logs/reports
      - name: Archive test logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: automation-logs
          path: target/cucumber-reports/**/*
